import type { ThemeDefinition } from './themeTokens';

export const aceStudioTheme: ThemeDefinition = {
  id: 'ace-studio',
  name: 'ACE Studio',
  description: 'Modern cool-toned dark theme (default)',
  tokens: {
    'daw-bg': '#191b1f',
    'daw-surface': '#1c1d22',
    'daw-surface-2': '#2a2a2a',
    'daw-surface-3': '#23262b',
    'daw-border': '#3a3d44',
    'daw-border-strong': '#1a1a1a',
    'daw-hover': '#35383f',
    'daw-hover-subtle': '#2f3238',
    'daw-text-muted': '#9aa0a8',
    'daw-accent': '#4a90d9',
    'daw-accent-hover': '#5ba3ec',
    'daw-playhead': '#5e59ff',
    'daw-arrangement-header-bg': '#1e1e2e',
    'daw-arrangement-group-bg': '#252538',
    'daw-arrangement-empty-lane-bg': '#1a1a2a',
    'daw-arrangement-separator': '#3e424c',
    'daw-grid-bar': '#6F7382',
    'daw-grid-beat': '#484A55',
    'daw-grid-eighth': '#2E3138',
    'daw-grid-sub': '#2E3138',
    'daw-track-selected': '#2e2c58',
    'daw-region-audio': '#4a8cc7',
    'daw-region-midi': '#5cb85c',
    'daw-region-drummer': '#d4a843',
    'daw-region-sample': '#9b59b6',
    'daw-scrollbar': '#4a4a4a',
    'daw-scrollbar-hover': '#5a5a5a',
    'daw-slider-thumb': '#4A5FFF',
    'daw-slider-thumb-hover': '#5B6FFF',
    'daw-focus-ring': 'rgba(74, 95, 255, 0.5)',
  },
};
